language: objective-c

before_install:
  - gem uninstall -Vax --force --no-abort-on-dependent run_loop

script:
  - scripts/ci/travis/install-gem-ci.rb
  - scripts/ci/travis/rspec-ci.rb

rvm:
  - 1.9.3
  - 2.1.0
  - 2.1.1

notifications:
  email:
    recipients:
      - joshuajmoody@gmail.com
      - karl.krukow@xamarin.com
    on_success: always # tmp for testing
    on_failure: change
